---
- name: Download zammad release
  get_url:
    url: https://ftp.zammad.com/zammad-latest.tar.gz
    dest: /tmp/zammad-latest.tar.gz
    mode: 0440

- name: Create zammad target directory
  file:
    path: /opt/zammad
    state: directory
    mode: 0775

- name: Unarchive zammad
  unarchive:
    src: /tmp/zammad-latest.tar.gz
    dest: /opt/zammad
    remote_src: yes

- name: Give zammad user permissions
  file:
    path: /opt/zammad
    owner: "{{ zammad_user }}"
    group: "{{ zammad_user }}"
    recurse: true

# Attention! Inverted logic: "without postgres" means "install with mysql"
- name: Install application dependencies with mysql database support
  shell: bundle install --path vendor/bundle --without test development postgres
  args:
    chdir: /opt/zammad
  when: zammad_db_mysql

# Attention! Inverted logic: "without mysql" means "install with postgres"
- name: Install dependencies with postgres database support
  shell: bundle install --path vendor/bundle --without test development mysql
  args:
    chdir: /opt/zammad
  when: zammad_db_postgresql

- name: After gem installation ensure that directory and contents belong to zammad user again
  file:
    path: /opt/zammad
    owner: "{{ zammad_user }}"
    group: "{{ zammad_user }}"
    recurse: true

- name: Ensure that all users are allowed to execute bundler
  file:
    path: /usr/local/bin/bundle
    mode: 0755

- name: Install zammad systemd services
  shell: ./install-zammad-systemd-services.sh
  args:
    chdir: /opt/zammad/script/systemd
  when: zammad_install_systemd_service
